version: "3"
services:
  api:
    container_name: uea-post-graduation-api-dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    image: uea-graduation-dev
    command: npm run start:debug
    restart: always
    volumes:
      - .:/usr/src/uea-graduation-api
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
      - "9229:9229"
